---
- name: Read in Variable Values from settings.yml
  include_vars:
    file: ../../settings.yml
    name: settings

- name: Debug settings
  debug:
    var: settings

- name: Update apt-get
  shell:
    cmd: "sudo apt-get update && touch ~/.apt-updated"
    creates: ~/.apt-updated

- name: Install required packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-virtualenv
#      - python3-psycopg2
#      - python3-psycopg2
      - apache2
      - apache2-dev
      - build-essential
      - git
#      - memcached
#      - postgresql-client-11
#      - postgresql-11
#      - netcat
      - libapache2-mod-wsgi-py3
  become: true


