---
- name: Read in Variable Values from settings.yml
  include_vars:
    file: ../../settings.yml
    name: settings

- name: Debug settings
  debug:
    var: settings

- name: Update apt-get
  shell:
    cmd: "apt-get update && touch ~/.apt-updated"
    creates: ~/.apt-updated

- name: Install required packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apache2
      - apache2-dev
      - apache2-utils
      - ssl-cert
      - build-essential
      - git
      - libapache2-mod-wsgi-py3
      - python3-setuptools
      - rsync

- name: create /etc/globus-portal if it doesn't exist
  file:
      path: /etc/globus-portal
      state: directory
      recurse: yes

- name: Render settings.yml
  template:
    src: settings.yml.j2
    dest: /etc/globus-portal/settings.yml
  notify: restart apache

- name: Debug current playbook_dir
  debug:
    var: playbook_dir

- name: Ensure sync destination exists
  file:
    path: /sites/django-globus-portal-framework/
    state: directory
    recurse: yes

- name: Sync repo into remote machine
  synchronize:
    src: "{{ playbook_dir }}/../"
    dest: "/sites/django-globus-portal-framework/"

- name: Create virtualvenv
  shell:
    cmd: "python3 -m venv /sites/django-globus-portal-framework/venv/"
    creates: "/sites/django-globus-portal-framework/venv/"

- name: Install django-globus-portal-framework requirements
  pip:
    requirements: "/sites/django-globus-portal-framework/requirements.txt"
    virtualenv: "/sites/django-globus-portal-framework/venv/"
  notify: restart apache

- name: render site apache settings
  template:
    src: globus-portal.conf.j2
    dest: /etc/apache2/sites-available/globus-portal.conf
  notify: restart apache

- name: enable site apache conf
  shell:
    cmd: "a2ensite globus-portal.conf"
    creates: /etc/apache2/sites-enabled/globus-portal.conf
  notify: restart apache

